### ISSUE TITLE
Clarification needed on where .gitignore should go

### ISSUE THREAD

**Issue by agentolivia** [DrupalizeMe/lesson-materials-template#2]
When downloading Drupal to docroot, a .gitignore is included. However, the repo is git init'd from the parent directory of docroot. PHPStorm adds a .idea file in that parent directory. I want to be able to add .idea to a .gitignore in the root directory of this repo. Is ok to have two .gitignores, one in the root of the repo and one in docroot?

cc: @eojthebrave

**Comment by eojthebrave** [comment]
Yeah, that should work fine. I believe they will both work and that Git will effectively cascade the ignore.

**Comment by agentolivia** [comment]
That worked fine. Thanks!
